/*
 * FrmDBTablesList.java
 *
 * Created on 05 September 2007, 13:51
 */
package com.MGenerator.Frams;

import com.MGenerator.DataBaseLayer.DBMetaData;
import com.MGenerator.DataBaseLayer.TableBean;
import com.MGenerator.Generators.Generator;
import com.MGenerator.metadata.SettingDetails;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author mohamed.metwally
 */
public class FrmDBTablesList extends javax.swing.JFrame {

    DefaultListModel dbTbllistModel;
    String saveToPath;
    HashMap tablesMap = null;

    /**
     * Creates new form FrmDBTablesList
     */
    public FrmDBTablesList(ArrayList tablesArrList) {
        //this.tablesArrList = tablesArrList;
        if (tablesArrList != null) {
            this.tablesMap = new HashMap();
            TableBean tblBean;
            for (int i = 0; i < tablesArrList.size(); i++) {
                tblBean = (TableBean) tablesArrList.get(i);
                tablesMap.put(tblBean.getTblName(), tblBean);
            }
        }
        initComponents();
        String tableName;
        this.defaultRDBtn.setActionCommand(this.defaultRDBtn.getText());
        this.addTemplateRDBtn.setActionCommand(this.addTemplateRDBtn.getText());
        dbTbllistModel = new DefaultListModel();
        for (int i = 0; i < tablesArrList.size(); i++) {
            tableName = ((TableBean) tablesArrList.get(i)).getTblName();
            dbTbllistModel.addElement(tableName);
            
        }
        this.dbTblList.setModel(dbTbllistModel);
        for (int i = 0; i < tablesArrList.size(); i++) {
            this.dbTblList.setSelectedIndex(i);
        }
        setFileChooserVisiblity(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        templateSave = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        dbTblList = new javax.swing.JList();
        genBtn = new javax.swing.JToggleButton();
        cancelBtn = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        defaultRDBtn = new javax.swing.JRadioButton();
        addTemplateRDBtn = new javax.swing.JRadioButton();
        fileChooserPnl = new javax.swing.JPanel();
        txtFile = new javax.swing.JTextField();
        browseBtn = new javax.swing.JButton();
        saveToTxt = new javax.swing.JTextField();
        saveToBtn = new javax.swing.JButton();
        daoPackage = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        contextPathTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        templateSave.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        templateSave.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        templateSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                templateSaveActionPerformed(evt);
            }
        });

        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(dbTblList);
        dbTblList.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 20, 300, 260);

        genBtn.setText("Generate");
        genBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genBtnActionPerformed(evt);
            }
        });
        getContentPane().add(genBtn);
        genBtn.setBounds(30, 550, 100, 23);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn);
        cancelBtn.setBounds(190, 550, 100, 23);

        jPanel1.setLayout(null);

        buttonGroup1.add(defaultRDBtn);
        defaultRDBtn.setText("Default");
        defaultRDBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        defaultRDBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        defaultRDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultRDBtnActionPerformed(evt);
            }
        });
        jPanel1.add(defaultRDBtn);
        defaultRDBtn.setBounds(10, 10, 110, 15);

        buttonGroup1.add(addTemplateRDBtn);
        addTemplateRDBtn.setSelected(true);
        addTemplateRDBtn.setText("Add Template");
        addTemplateRDBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        addTemplateRDBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        addTemplateRDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTemplateRDBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addTemplateRDBtn);
        addTemplateRDBtn.setBounds(10, 30, 110, 20);

        fileChooserPnl.setLayout(null);
        fileChooserPnl.add(txtFile);
        txtFile.setBounds(-20, 0, 320, 20);

        jPanel1.add(fileChooserPnl);
        fileChooserPnl.setBounds(20, 60, 270, 30);

        browseBtn.setText("Browse");
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });
        jPanel1.add(browseBtn);
        browseBtn.setBounds(320, 60, 90, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 290, 410, 100);
        getContentPane().add(saveToTxt);
        saveToTxt.setBounds(20, 490, 200, 20);

        saveToBtn.setText("Save");
        saveToBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveToBtn);
        saveToBtn.setBounds(220, 490, 80, 23);
        getContentPane().add(daoPackage);
        daoPackage.setBounds(200, 440, 170, 20);

        jLabel1.setText("Datalayer Package");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 440, 120, 20);

        jLabel3.setText("Tables");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 20, 50, 20);
        getContentPane().add(contextPathTxt);
        contextPathTxt.setBounds(200, 400, 170, 20);

        jLabel2.setText("ContextPath");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 400, 120, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        if (!evt.getActionCommand().equals("CancelSelection")) {
            this.txtFile.setText(jFileChooser1.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        jFileChooser1.showOpenDialog(this);
    }//GEN-LAST:event_browseBtnActionPerformed

    private void defaultRDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultRDBtnActionPerformed
        setFileChooserVisiblity(false);
    }//GEN-LAST:event_defaultRDBtnActionPerformed

    private void addTemplateRDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTemplateRDBtnActionPerformed
        setFileChooserVisiblity(true);
    }//GEN-LAST:event_addTemplateRDBtnActionPerformed

    private void genBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genBtnActionPerformed
        try {
            Object[] selectedTbls = null;
            if (saveToPath.equals("")) {
                JOptionPane.showMessageDialog(this, "You have to select path to save to");
                return;
            } else {
                if (this.dbTblList != null) {
                    selectedTbls = this.dbTblList.getSelectedValues();
                }
                String daoPackage = this.daoPackage.getText();
                String contextPath = this.contextPathTxt.getText();
                String modelsPackage = this.daoPackage.getText();
                DBMetaData dbMetaData = GenMain.dbBase.getDBMetaData();
                TableBean tblBean;
                Generator generator = new Generator();
                ArrayList<TableBean> selectedTables = new ArrayList<TableBean>();                
                for (int i = 0; i < selectedTbls.length; i++) {
                    try {
                        tblBean = (TableBean) this.tablesMap.get(selectedTbls[i].toString());                        
                        selectedTables.add(tblBean);
                    } catch (Exception ex) {
                    }
                }
                SettingDetails settingDetails = new SettingDetails();
                settingDetails.setDaoPackage(daoPackage);
                settingDetails.setIsDefault(false);
                settingDetails.setModelsPackage(modelsPackage);
                settingDetails.setOutPath(saveToPath);
                settingDetails.setTbls(selectedTables);
                settingDetails.setTemplatePath(txtFile.getText());
                settingDetails.setContextPath(contextPath);  
                for(TableBean tableBean: settingDetails.getTbls()){
                    generator.generate(tableBean, settingDetails);
                }
                generator.generate(settingDetails);
                JOptionPane.showMessageDialog(this, "Generation Done please check output folder");
                this.setVisible(false);
                this.dispose();
            }
        } catch (ClassNotFoundException ex) {
            //LoggingClass.logInfo(ex.toString());
        } catch (SQLException ex) {
            //LoggingClass.logInfo(ex.toString());
        }

    }//GEN-LAST:event_genBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveToBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToBtnActionPerformed
        templateSave.showSaveDialog(this);
    }//GEN-LAST:event_saveToBtnActionPerformed

    private void templateSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_templateSaveActionPerformed
        if (!evt.getActionCommand().equals("CancelSelection")) {
            this.saveToTxt.setText(templateSave.getSelectedFile().getPath());
            this.saveToPath = this.saveToTxt.getText();
        }
    }//GEN-LAST:event_templateSaveActionPerformed

    public void setFileChooserVisiblity(boolean flag) {
        this.browseBtn.setVisible(flag);
        this.txtFile.setVisible(flag);
        this.fileChooserPnl.setVisible(flag);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addTemplateRDBtn;
    private javax.swing.JButton browseBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton cancelBtn;
    private javax.swing.JTextField contextPathTxt;
    private javax.swing.JTextField daoPackage;
    private javax.swing.JList dbTblList;
    private javax.swing.JRadioButton defaultRDBtn;
    private javax.swing.JPanel fileChooserPnl;
    private javax.swing.JToggleButton genBtn;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveToBtn;
    private javax.swing.JTextField saveToTxt;
    private javax.swing.JFileChooser templateSave;
    private javax.swing.JTextField txtFile;
    // End of variables declaration//GEN-END:variables
}
