/*
 * OraTest.java
 *
 * Created on 28 August 2007, 12:23
 */

package com.MGenerator.Frams;

import com.MGenerator.DataBaseLayer.DBBase;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author  mohamed.metwally
 */
public class GenMain extends javax.swing.JFrame {
    
    /** Creates new form OraTest */
    public GenMain() {
        initComponents();
        this.TestBtn.setVisible(false);
        this.jButton1.setVisible(false);
        hideValidateLabels();
        this.oracleRdBtn.setActionCommand(this.oracleRdBtn.getText());
        this.msSqlRdBtn.setActionCommand(this.msSqlRdBtn.getText());
        this.mySqlRdBtn.setActionCommand(this.mySqlRdBtn.getText());
        this.hSqlRdBtn.setActionCommand(this.hSqlRdBtn.getText());
    }
    private String connectionString;
    private String driverString;
    private String userName;
    private String password;
    private Connection conn;
    FrmDBTablesList frmTblList;
    public static DBBase dbBase;
    public static int dbType;
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        TestBtn = new javax.swing.JButton();
        txtServerName = new javax.swing.JTextField();
        txtDBSchema = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        oracleRdBtn = new javax.swing.JRadioButton();
        msSqlRdBtn = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        mySqlRdBtn = new javax.swing.JRadioButton();
        hSqlRdBtn = new javax.swing.JRadioButton();
        generateBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPortNum = new javax.swing.JTextField();
        lblServerName = new javax.swing.JLabel();
        lblDBSchema = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblPortNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        TestBtn.setText("Test Ora");
        TestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestBtnActionPerformed(evt);
            }
        });
        getContentPane().add(TestBtn);
        TestBtn.setBounds(350, 70, 120, 23);

        txtServerName.setText("127.0.0.1");
        txtServerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServerNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtServerName);
        txtServerName.setBounds(200, 20, 100, 20);
        getContentPane().add(txtDBSchema);
        txtDBSchema.setBounds(200, 60, 100, 20);

        txtUserName.setText("root");
        getContentPane().add(txtUserName);
        txtUserName.setBounds(200, 100, 100, 20);

        jLabel1.setText("Server Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 90, 14);

        jLabel2.setText("Db Schema");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 100, 14);

        jLabel3.setText("User Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 90, 20);

        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 150, 90, 14);

        txtPassword.setText("root");
        getContentPane().add(txtPassword);
        txtPassword.setBounds(200, 150, 100, 20);

        jButton1.setText("TestSQL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(360, 30, 90, 23);

        jPanel1.setLayout(null);

        btnGroup.add(oracleRdBtn);
        oracleRdBtn.setText("Oracle");
        oracleRdBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        oracleRdBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        oracleRdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oracleRdBtnActionPerformed(evt);
            }
        });
        jPanel1.add(oracleRdBtn);
        oracleRdBtn.setBounds(10, 40, 130, 15);

        btnGroup.add(msSqlRdBtn);
        msSqlRdBtn.setText("MS Sql Server");
        msSqlRdBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        msSqlRdBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        msSqlRdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msSqlRdBtnActionPerformed(evt);
            }
        });
        jPanel1.add(msSqlRdBtn);
        msSqlRdBtn.setBounds(10, 70, 140, 15);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Data Base Type");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 180, 20);

        btnGroup.add(mySqlRdBtn);
        mySqlRdBtn.setSelected(true);
        mySqlRdBtn.setText("mySql");
        mySqlRdBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        mySqlRdBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        mySqlRdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mySqlRdBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mySqlRdBtn);
        mySqlRdBtn.setBounds(10, 100, 120, 15);

        btnGroup.add(hSqlRdBtn);
        hSqlRdBtn.setText("HSql");
        hSqlRdBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        hSqlRdBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        hSqlRdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hSqlRdBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hSqlRdBtn);
        hSqlRdBtn.setBounds(10, 130, 120, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 290, 220, 150);

        generateBtn.setText("Connect");
        generateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(generateBtn);
        generateBtn.setBounds(330, 360, 90, 23);

        jLabel6.setText("PortNum");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 190, 90, 14);

        txtPortNum.setText("3306");
        getContentPane().add(txtPortNum);
        txtPortNum.setBounds(200, 190, 100, 20);

        lblServerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblServerName.setForeground(new java.awt.Color(255, 0, 0));
        lblServerName.setText("*");
        getContentPane().add(lblServerName);
        lblServerName.setBounds(310, 20, 20, 14);

        lblDBSchema.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDBSchema.setForeground(new java.awt.Color(255, 0, 0));
        lblDBSchema.setText("*");
        getContentPane().add(lblDBSchema);
        lblDBSchema.setBounds(310, 60, 20, 14);

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 0, 0));
        lblUserName.setText("*");
        getContentPane().add(lblUserName);
        lblUserName.setBounds(310, 100, 20, 14);

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 0, 0));
        lblPassword.setText("*");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(310, 150, 20, 14);

        lblPortNum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPortNum.setForeground(new java.awt.Color(255, 0, 0));
        lblPortNum.setText("*");
        getContentPane().add(lblPortNum);
        lblPortNum.setBounds(310, 190, 20, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hSqlRdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hSqlRdBtnActionPerformed
        this.txtPortNum.setText("");
        dbType = Integer.parseInt(ResourceBundle.getBundle("DataBaseTypes").getString("hsql"));
    }//GEN-LAST:event_hSqlRdBtnActionPerformed

    private void mySqlRdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mySqlRdBtnActionPerformed
        this.txtPortNum.setText("3306");
        dbType = Integer.parseInt(ResourceBundle.getBundle("DataBaseTypes").getString("mysql"));        
    }//GEN-LAST:event_mySqlRdBtnActionPerformed
   
    private void msSqlRdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msSqlRdBtnActionPerformed
        this.txtPortNum.setText("1433");
        dbType = Integer.parseInt(ResourceBundle.getBundle("DataBaseTypes").getString("mssqlserver"));
    }//GEN-LAST:event_msSqlRdBtnActionPerformed

    private void oracleRdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oracleRdBtnActionPerformed
        this.txtPortNum.setText("1521");
        dbType = Integer.parseInt(ResourceBundle.getBundle("DataBaseTypes").getString("oracle"));
    }//GEN-LAST:event_oracleRdBtnActionPerformed

    private void generateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBtnActionPerformed
        int type = getSelectedDBType();        
        if(validateFields()){
            dbBase = new DBBase(this.txtServerName.getText(),this.txtDBSchema.getText(),this.txtUserName.getText(),this.getTxtPassword().getText(),this.txtPortNum.getText(),type);
            try {
                conn = dbBase.instanceOfConnection();
                frmTblList = new FrmDBTablesList(dbBase.getMetaData(conn));
                frmTblList.setSize(600,800);
                frmTblList.setVisible(true);                
                dbBase.closeConnection();
                this.dispose();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"connection Error :: " + ex.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
            } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(this,"connection Error :: " + ex.getMessage(),"error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_generateBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //jdbc:microsoft:sqlserver:M_METWALLY:1433;databaseName=JavaCodeSmit;
            
        this.setDriverString("com.microsoft.jdbc.sqlserver.SQLServerDriver");
        this.setConnectionString("jdbc:microsoft:sqlserver://"+this.txtServerName.getText()+":1433;databaseName="+this.txtDBSchema.getText()+";");
        this.setUserName(this.txtUserName.getText());
        this.setPassword(this.txtPassword.getText());
        createConnection();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestBtnActionPerformed
        this.setDriverString("oracle.jdbc.driver.OracleDriver");
        this.setConnectionString("jdbc:oracle:thin:@"+this.txtServerName.getText()+":1521:"+this.getTxtDBSchema().getText());
        this.setUserName(this.txtUserName.getText());
        this.setPassword(this.txtPassword.getText());
        createConnection();
    }//GEN-LAST:event_TestBtnActionPerformed

    private void txtServerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServerNameActionPerformed
   
    
    void hideValidateLabels(){
        this.lblDBSchema.setVisible(false);
        this.lblServerName.setVisible(false);
        this.lblUserName.setVisible(false);
        this.lblPassword.setVisible(false);
        this.lblPortNum.setVisible(false);
    }
    
    boolean validateFields(){
        if(this.txtServerName.getText().equals("")){
            hideValidateLabels();
            this.lblServerName.setVisible(true);            
            return false;
        }  
        if(this.txtDBSchema.getText().equals("")){
            hideValidateLabels();
            this.lblDBSchema.setVisible(true);            
            return false;
        } 
        if(this.txtUserName.getText().equals("")){
            hideValidateLabels();
            this.lblUserName.setVisible(true);            
            return false;
        } 
        if(this.txtPortNum.getText().equals("")){
            hideValidateLabels();
            this.lblPortNum.setVisible(true);            
            return false;
        } 
        if(this.txtPassword.getText().equals("")){
            int selection = JOptionPane.showConfirmDialog(this,"are you sure that the password is blank?","confirm",JOptionPane.YES_NO_OPTION);
            if(selection == JOptionPane.YES_OPTION)
                return true;
            else{                            
                hideValidateLabels();
                this.lblPassword.setVisible(true);            
                return false;
            }
        } 
        return true;
    }
    
   int getSelectedDBType(){
       String btnCommand = this.btnGroup.getSelection().getActionCommand();
       if(btnCommand.equals(this.oracleRdBtn.getText())){
           return 1;
           
       }else if(btnCommand.equals(this.msSqlRdBtn.getText())){
           return 2;
       }else if(btnCommand.equals(this.hSqlRdBtn.getText())){
           return 4;
       }else if(btnCommand.equals(this.mySqlRdBtn.getText())){
           return 3;
       }
       return -1;
   }
    
    public void createConnection(){
        try{
            
            //Class.forName("com.microsoft.jdbc.sqlserver.SQLServerDriver");
            Class.forName(getDriverString());
            
        }catch(Exception ex){
            System.err.println("cant register driver " + ex.getMessage() );
        }
        
        try {
                setConn(DriverManager.getConnection(getConnectionString(), getUserName(), getPassword()));
                System.err.println("connection established");
                //DatabaseMetaData metaData = conn.getMetaData();
            
        } catch (SQLException ex) {
            System.err.println("Connection Error :: "+ ex.getMessage() );
        }
        
    }    

    public String getConnectionString() {
        return connectionString;
    }

    public void setConnectionString(String connectionString) {
        this.connectionString = connectionString;
    }

    public String getDriverString() {
        return driverString;
    }

    public void setDriverString(String driverString) {
        this.driverString = driverString;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Connection getConn() {
        return conn;
    }

    public void setConn(Connection conn) {
        this.conn = conn;
    }

    public javax.swing.JButton getTestBtn() {
        return TestBtn;
    }

    public void setTestBtn(javax.swing.JButton TestBtn) {
        this.TestBtn = TestBtn;
    }

    public javax.swing.JLabel getJLabel1() {
        return jLabel1;
    }

    public void setJLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public javax.swing.JLabel getJLabel2() {
        return jLabel2;
    }

    public void setJLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public javax.swing.JLabel getJLabel3() {
        return jLabel3;
    }

    public void setJLabel3(javax.swing.JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public javax.swing.JLabel getJLabel4() {
        return jLabel4;
    }

    public void setJLabel4(javax.swing.JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public javax.swing.JTextField getTxtDBSchema() {
        return txtDBSchema;
    }

    public void setTxtDBSchema(javax.swing.JTextField txtDBSchema) {
        this.txtDBSchema = txtDBSchema;
    }

    public javax.swing.JTextField getTxtPassword() {
        return txtPassword;
    }

    public void setTxtPassword(javax.swing.JTextField txtPassword) {
        this.txtPassword = txtPassword;
    }

    public javax.swing.JTextField getTxtUserName() {
        return txtUserName;
    }

    public void setTxtUserName(javax.swing.JTextField txtUserName) {
        this.txtUserName = txtUserName;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TestBtn;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton generateBtn;
    private javax.swing.JRadioButton hSqlRdBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDBSchema;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPortNum;
    private javax.swing.JLabel lblServerName;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JRadioButton msSqlRdBtn;
    private javax.swing.JRadioButton mySqlRdBtn;
    private javax.swing.JRadioButton oracleRdBtn;
    private javax.swing.JTextField txtDBSchema;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPortNum;
    private javax.swing.JTextField txtServerName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
    
}
