/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smp.frams.panels;

import {daoPkName}.dao.*;
import {daoPkName}.model.*;
import com.smp.frams.models.*;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author mmetwally
 */
public class {className}Panel extends javax.swing.JPanel {

    /**
     * Creates new form ProductPanel
     */
    public {className}Panel() {
        initComponents();
		initCustom();
    }


public void initCustom(){
        {className}TableModel.get{className}sTable({classNamelow}Table);
	{creatCustom}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        {classNamelow}Table = new javax.swing.JTable();
        {classNamelow}Panel = new javax.swing.JPanel();
        insertBtn = new javax.swing.JButton();
        msgLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jScrollPane1.setViewportView({classNamelow}Table);
        {classNamelow}Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("{classNamelow}"));
        insertBtn.setText("Insert");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });
		msgLabel.setVisible(false);        
        msgLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(255, 0, 0));
        msgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/error.jpg"))); // NOI18N
		{createLabel}
		{createProp}
        javax.swing.GroupLayout {classNamelow}PanelLayout = new javax.swing.GroupLayout({classNamelow}Panel);
        {classNamelow}Panel.setLayout({classNamelow}PanelLayout);
        {classNamelow}PanelLayout.setHorizontalGroup(
            {classNamelow}PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup({classNamelow}PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup({classNamelow}PanelLayout.createSequentialGroup()

                .addGroup({classNamelow}PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup({classNamelow}PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup({classNamelow}PanelLayout.createSequentialGroup()
                        .addGroup({classNamelow}PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
		{addprop}
	)		

                .addContainerGap())))
        );
        {classNamelow}PanelLayout.setVerticalGroup(
            {classNamelow}PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, {classNamelow}PanelLayout.createSequentialGroup()
                .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
		{addpropvertical}
                
				.addGap(18, 18, 18)
                .addComponent(insertBtn)
                .addContainerGap())
        );

        saveBtn.setText("save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent({classNamelow}Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saveBtn)
                        .addGap(38, 38, 38)
                        .addComponent(deletebtn)
                        .addGap(239, 239, 239))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deletebtn)
                            .addComponent(saveBtn))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent({classNamelow}Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    public void emptyFields() {        
		{emptyFields}
    }
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        {className}TableModel model = ({className}TableModel) {classNamelow}Table.getModel();
        //jTextArea1.setText("");
        if (model.getUpdatedIds() != null && !model.getUpdatedIds().isEmpty()) {
            for (int i = 0; i < model.getUpdatedIds().size(); i++) {
				{className} {classNamelow} = model.get{className}(model.getUpdatedIds().get(i));
				{className}DAO.updateByPrimaryKeySelective({classNamelow});
                //  jTextArea1.append(model.getUpdatedIds().get(i) + "\n");
            }
			model.getUpdatedIds().clear();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        //Integer rows = {classNamelow}Table.getRowCount();
        Boolean checkselected = false;
        // String deleteStr = "";

        for (int i = 0; i < (({className}TableModel) {classNamelow}Table.getModel()).getRowCount(); i++) {
            checkselected = Boolean.parseBoolean({classNamelow}Table.getValueAt(i, 0).toString());
            if (checkselected) {
				{className}DAO.deleteById(Integer.parseInt({classNamelow}Table.getValueAt(i, 1).toString()));				
                (({className}TableModel) {classNamelow}Table.getModel()).removeRow(i);
                {classNamelow}Table.revalidate();
                i--;
            }
        }
    }//GEN-LAST:event_deletebtnActionPerformed


    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        {className} {classNamelow}Obj = new {className}();      
        {insertprop}
		{className}DAO.insertSelective({classNamelow}Obj);
        {className}TableModel model = ({className}TableModel) {classNamelow}Table.getModel();
        model.addRow({classNamelow}Obj);
        {classNamelow}Table.revalidate();
        emptyFields();
    }//GEN-LAST:event_insertBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton insertBtn;
	{defineLabel}
	{defineprop}

    private javax.swing.JPanel {classNamelow}Panel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable {classNamelow}Table;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
